[package]
name = "bochservisor"
version = "0.1.0"
authors = ["Brandon Falk <bfalk@gamozolabs.com>"]
edition = "2018"

[dependencies]
whvp_bindings = { path="../whvp_bindings" }

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = true
